apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker
spec:
  selector:
    matchLabels:
      app: citus-workers
  serviceName: citus-workers
  replicas: 1
  template:
    metadata:
      labels:
        app: citus-workers
    spec:
      containers:
        - name: citus-worker
          image: dimitris007/test:latest
          imagePullPolicy: "IfNotPresent"
          args:
            - -c
            - max_locks_per_transaction=128
            - -c
            - shared_preload_libraries=citus,postgis-2.5.so
            - -c
            - ssl=on
            - -c
            - ssl_cert_file=/etc/postgresql-secrets-vol/server.crt
            - -c
            - ssl_key_file=/etc/postgresql-secrets-vol/server.key
          ports:
            - containerPort: 5432
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 7;printf \"local all all trust\nhost all all 127.0.0.1/32 trust\nhost all all ::1/128 trust\nhost all all 0.0.0.0/0 trust\n\" > /var/lib/postgresql/data/pg_hba.conf; psql -U postgresadmin -d postgres  --command=\"CREATE EXTENSION citus CASCADE;\"; psql -U postgresadmin -d postgres  --command=\"CREATE EXTENSION MobilityDB CASCADE;\"; psql -U postgresadmin -d postgres  --command=\"select pg_reload_conf();\"; PGPASSWORD=admin123 psql --host=citus-master -U postgresadmin -d postgres --command=\"SELECT * from master_add_node('${HOSTNAME}.citus-workers', 5432);\";"]
          #      command: ["/bin/sh", "-c", "sleep 5;psql -U postgresadmin -d postgres --command \"SELECT * from cars;\""]
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /etc/postgresql-secrets-vol
              name: secret-vol
      securityContext:
        runAsUser: 0
        supplementalGroups: [999,1000]
        fsGroup: 999
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: secret-vol
          secret:
            secretName: postgresql-secrets 
            defaultMode: 0640
